### PR TITLE
[do not merge] Upgrade base WildFly image to version 11.0.0.Final

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Review by romartin — APPROVED** [review]
Hey @cristianonicolai ,
It sounds good for me. Just as a note, not sure if you already checked it, but notice on each module there exist an `etc` package which contains the Wildfly (or whatever app server) configuration files (updated with some custom configurations). So for example you can find [here](https://github.com/kiegroup/kie-docker-ci-images/blob/master/kie-drools-wb/src/main/docker/wildfly/etc/standalone-full-kie-drools-wb.xml) the standalone configuration. As we're moving a major version it's possible that the configuration file from Widfly `10.1.x` to `11.0.x` differ... so in that case I used to compare both configuration files and apply the diffs, so keeping the latest config file but with our required custom configurations...
Anyway not sure if it applies in this situation, but probably worth doing it a quick look. 
Lemme know if I can help!!
Thanks!

**Comment by cristianonicolai** [comment]
@romartin I was about to update these PRs with the xml :)

**Comment by romartin** [comment]
hehe great np! And sorry for late review... I'm doing some workshop and a bit busy... Thanks!! )

**Comment by cristianonicolai** [comment]
@romartin all good, thanks! I will just hold these until master actually moves to WF11.

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Pull request merged**
