### PR TITLE
bumped up version to 7.10.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
@cristianonicolai can you approve this one in absence (PTO) of Roger

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
