### PR TITLE
WildFly 10 upgrade + remove EAP 6.4 images

### PR DESCRIPTION
**Pull request by psiroky**
@romartin could you please take a look?

### CODE REVIEW

**Comment by romartin** [comment]
oh @psiroky great work! really expecting to check this! but on the other hand absolutely busy this week for summit... :( is good for you merging next week please?

**Comment by romartin** [comment]
Hi @psiroky , trying to merge this now but geeing some missing dependency version errors... not sure yet what's the root issue, probably you can give me a clue with a quick look, as I think it's about some incorrect parent version and you're the man on this :) Any ideas? that's my local build log https://gist.github.com/romartin/6d75372e3279edf5f7438c47c0316c1c 
Thanks!

**Comment by romartin** [comment]
hi @psiroky just removed a comment here, it was my fault sorry :) trying to merge now

**Comment by psiroky** [comment]
@romartin TBH I am not sure the images work right now. There is bug in UF https://issues.jboss.org/browse/UF-335 which seems to break quite a lot of things.

**Comment by psiroky** [comment]
@romartin I did some minor changes to workaround https://issues.jboss.org/browse/JBEAP-2947 and the images/container work OK for me locally. Could you please just double check if it works for you as well? (or if you are busy, just let me know, I will push the changes and test them on the "production" instance :))

**Comment by romartin** [comment]
Hi @psiroky ( @csadilek you're asking for this as well )
I have tested and merged aa43813e9490acf99182c316523de898f686bed6 , great work Petr!! Only some minor things:
- I have added the commit 6407d6bccbbd6b7e9fa5c41bfb826f998ea381a6 to make the rest api available for kie-server ( see https://github.com/jboss-dockerfiles/drools/pull/10 as well )
- KIE Drools WB on W10 responds with a blank page after login ( redirects to /j_security_check and blank page appears). No exceptions on server side, on the other hand this error is not first time I see... but still dont remember, probably some minor webapp security config issue on the DD...
- Dashbuilder on Tomcat8 doesn't work. It produces this server logs -> https://gist.githubusercontent.com/romartin/abaa7568b823593b2d5a0225507117c4/raw/0783d8ee0a57d537c3cc1a4a076209be3b240af1/gistfile1.txt Probably missing weld artifacts on the classpath?

Anyway it works great in general, and it's better than we have now! So thanks and let's see now what jenkins and the ci webapp will do....

**Comment by psiroky** [comment]
Thanks @romartin! The Dashbuilder WAR will need to be fixed directly in the dashbuilder repo, right? Could you look please into that? 

KIE Drools WB works for me locally, and also on the Docker server. Could this be some env issue?

I am also closing the PR as the changes were merged.

**Pull request closed without merging**
