### PR TITLE
JBPM-6671 - Add kie-server to kie-wb and kie-drools-wb images

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@psiroky @mbiarnes adding the kie server deployment so that the image can be used for quick demos and also for reproducing issues communicating with the kie server is needed.

**Comment by psiroky** [comment]
If we bundle both WB and KIE Server into single image, then I think the image name should be changed to follow that. 

Just an idea: wouldn't it be better to keep them as separate images and glue them together with something like docker-compose?

**Comment by cristianonicolai** [comment]
@psiroky sure, what do you suggest as the image name? (kie-wb-kie-server-wildfly10?) If we change the image name, does that impact the UI part somehow?

As for the using docker compose, I think it is a good idea but as far as this specific use in CI/CD, I understood the goal is the keep it as simple as possible, so self-contained, without any orchestration.

**Comment by cristianonicolai** [comment]
please note that I had to change the default admin user to wbadmin/wbadmin, that is needed for avoiding jBPM Human Task API to colide with having a user (admin) and a group/role (admin) with the same name.

**Comment by cristianonicolai** [comment]
cc @nmirasch @bsremac

**Comment by psiroky** [comment]
I will no longer be maintaining these images, so the name is up to you (or someone else who is going to be maintaining these). `kie-wb-kie-server-wildfly10` looks OK.

**Comment by bsremac** [comment]
+1 for the naming scheme. I think it's good that the name says it clear what is in it, although it might seem a bit clunky.

Two questions:
1. Is it worth including these new images for Tomcat, taking that we stopped supporting any other container except for Wildfly/EAP for _kie-drools-wb_ and _kie-wb_? (_kie-server_ continues to be supported on multiple containers on the other hand).

2. Is there any value in adding _kie-server_ role to users for _kie-drools-wb_ image, as there are no runtime views exposed in _kie-drools-wb_?

**Comment by cristianonicolai** [comment]
np, I'll update the image names to match what we discussed here. @psiroky or @romartin  would you guys know if that can break the Docker UI app and how do we get these changes updated in the app?

@bsremac In regards to Tomcat support, we still have community wars so I think that somehow it still helps to have these images and test it end to end when needed. As for the _kie-server_ role, you might be right, we probably don't need those.

**Comment by psiroky** [comment]
@cristianonicolai sorry, no idea. You could probably try to run the container + the app locally to see if it's able to pick-up the new container.

**Comment by romartin** [comment]
@cristianonicolai mmm lemme look a little bit, not sure yet...so what's going to change? the name for the resulting `war` artifacts?

**Comment by romartin** [comment]
@cristianonicolai well just doing a quick check I would say that if you change the war artifact name we have to fix the docker stuff yes, but probably @mbiarnes can confirm, as he has other `shell` scripts as well....
The docker CI stuff basically relies on 2 things:
- The maven artifact names (you'll have to fix the `pom`'s, assemblies, etc if so, look [here](https://github.com/kiegroup/kie-docker-ci/blob/master/pom.xml) or [here](https://github.com/kiegroup/kie-docker-ci-images/blob/master/pom.xml))
- For the concrete KIE CI webapp there also exist a few "hardcodings"... that probably have to change as well, for example look [here](https://github.com/kiegroup/kie-docker-ci/blob/master/kie-docker-ui-webapp/src/main/java/org/kie/dockerui/shared/model/impl/KieWorkbenchType.java#L8) or [here](https://github.com/kiegroup/kie-docker-ci/blob/master/kie-docker-ui-webapp/src/main/java/org/kie/dockerui/shared/model/impl/KieDroolsWorkbenchType.java#L8)

BTW remember to check as well with @mbiarnes  the `shell` scripts.
Anyway if you need help at some point just ping me, np!! :+1:

**Comment by cristianonicolai** [comment]
@romartin thanks for the pointers, I manage to test it locally and it seems to be working fine as the maven artifacts still with the same name, only changed part of the image name which still under the same prefix. Seems fine also with most scripts too. I did find some issues but they seem unrelated to this change.
@mbiarnes mind taking a quick look on this in case I missing anything. Would like to push these changes in our environment.

**Comment by mbiarnes** [comment]
@romartin @cristianonicolai 
My scripts pick up what is there in github, so each change you do here it will be also in my scripts.
Should work.
Another thing is that we have to sync the images in docker-hub - but this we will do when we have the next Final release.

**Comment by cristianonicolai** [comment]
@romartin @mbiarnes  sounds like is mostly fine, can we merge this and give it a go in our environment, wdyt?

**Comment by mbiarnes** [comment]
@cristianonicolai @romartin yepp - today everything is running - the PR is green  - so go ahead. In worst case if we see tomorrow that the Docker images are not build automatically we can revert this PR.

**Comment by cristianonicolai** [comment]
@mbiarnes great, thanks! Will get it merged now, please let me know in case there are any issues with building these Docker images.

**Comment by mbiarnes** [comment]
@cristianonicolai OK - we will see tomorrow morning :)

**Comment by mbiarnes** [comment]
@cristianonicolai I looked this morning. But since kieAllBuild fails fro 7.5.x and master (Jenkins failures and jbpm) the docker jobs weren't triggered. So we have to wait until the next SUCCESSFUL build.

**Comment by cristianonicolai** [comment]
@mbiarnes no problem, let's see if it works today :)

**Comment by mbiarnes** [comment]
@cristianonicolai seem to be ok - the jobs run

**Pull request merged**
