### PR TITLE
updated Dockerfiles to use wildfly:19.1.0.Final

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
what about readme files or comments mentioning WF 18 ?

**Comment by mareknovotny** [comment]
so after backporting of change deployable classificator, there is at least this https://github.com/mbiarnes/kie-docker-ci-images/blame/wildfly19-7.39.x/README.md#L33 and this required change https://github.com/mbiarnes/kie-docker-ci-images/blob/wildfly19-7.39.x/kie-artifacts/pom.xml#L21

**Comment by mbiarnes** [comment]
@mareknovotny all changed from wildfly18 to wildfly19 - no confusion any more

**Review by mareknovotny — APPROVED** [review]
lgtm

**Pull request merged**
