### PR TITLE
Add kie-server + WildFly 10 Docker image

### PR DESCRIPTION
**Pull request by psiroky**
@romartin could you please review this?

I basically took the standalone-full.xml from WFLY10 and added the custom changes there (as that is much easier than trying to fix the current config).

### CODE REVIEW

**Comment by romartin** [comment]
@psiroky oh thanks! I will review tomorrow as I don't have my other laptop with latest docker daemon  here today, sorry.

**Comment by romartin** [comment]
@psiroky Hello, I build it locally and sounds good. There are still missing the other images to migrate to latest versions, so not sure if you want me to merge this one or not right now....

**Comment by psiroky** [comment]
Yeah, creating the images is not that hard. Creating the actual wars is far worse. We (I) will need to create the kie-wb WFLY10 wars and then can submit next PR.

**Comment by romartin** [comment]
@psiroky okkk good, so better let's wait for the others. I you need something just let me know :)

**Comment by psiroky** [comment]
@romartin so you want to leave this PR open until we have the other WFLY10 images as well? I would be for merging this PR as it is quite self-contained and we could start building the and running images to make sure everything works as expected.

**Comment by romartin** [comment]
@psiroky well yes, you're right, it's self-contained np. Yeahh sounds good, do you want me to merge it then?

**Comment by psiroky** [comment]
@romartin yes please. Or you can just comment with +1 and I will merge it then.

**Comment by romartin** [comment]
@psiroky Merged: c3348d20fe486ddccd7e7fb374c3d42b1f79622f Thanks!

**Pull request closed without merging**
