### PR TITLE
[GUVNOR-2889] rename 'kie-wb-distribution-wars-*.war' to 'kie-wb-*.war'

### PR DESCRIPTION
**Pull request by psiroky**
Needs to be merged after the following PRs are merged as well:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/398
https://github.com/droolsjbpm/jbpm/pull/763
https://github.com/droolsjbpm/kie-wb-distributions/pull/469

### CODE REVIEW

**Comment by manstis** [comment]
@romartin The PR looks OK to me (based on what I can see to be simple updates); could however you approve this PR (in case you know there's more changes needed!?!)

**Comment by psiroky** [comment]
I've tested the changes locally while ago and everything seemed to work.

~~There is no PR job for this repo yet, so the automated build won't run.~~ I just created the PR job, so lets see how the build goes.

**Comment by romartin** [comment]
@psiroky @manstis looking, but it will take some time, i have to build the dependant PRs and configure my docker environment locally (just reinstalled OS)... so will let you know asap!

**Comment by psiroky** [comment]
@romartin I don't think you need to do that...This really is just rename of the WARs. So if the build works I would say its fine.

In the rare case something would go wrong, we can still do the fix later (this is not on of the blessed repos, so will not block the release in any way).

**Review by romartin — APPROVED** [review]
thanks @psiroky , I'm having issues now with the docker daemon and do not have much time to spend today on this sorry. Changes look good to me, I was just to try to double check.. so go ahead! :+1:

**Pull request merged**
